In [3]:
import tensorflow as tf
import numpy as np

In [4]:
def bpmll(predict,ground_truth):
    num_pos_class=tf.reduce_sum(ground_truth,1)
    num_neg_class=num_classes- num_pos_class

    print(num_pos_class.eval())
    print(num_neg_class.eval())
    factor=1/(num_pos_class*num_neg_class)
    
    print(factor)
    print(factor.eval())
    print(predict)
    print(predict.eval())
    print(ground_truth)
    print(ground_truth.eval())


    predict_boardcast_subtrahend=tf.tile(predict,[1,1,num_classes])
    # predict_boardcast_subtrahend=tf.concat([predict]*num_classes, 2)
    predict_boardcast_minuend=tf.transpose(predict_boardcast_subtrahend,perm=[0,2,1])

    print(predict_boardcast_subtrahend)
    print(predict_boardcast_subtrahend.eval())
    print(predict_boardcast_minuend)
    print(predict_boardcast_minuend.eval())

    ground_truth=tf.reshape(ground_truth,[batch_size,num_classes,1])
    ground_truth_boardcast=tf.tile(ground_truth,[1,1,num_classes])
    ground_truth_boardcast_nimei=tf.transpose(ground_truth_boardcast,perm=[0,2,1])
    mask=ground_truth_boardcast*(1 - ground_truth_boardcast_nimei)
    print('mask')
    print(mask.eval())

    loss=factor*tf.reduce_sum(tf.exp(-1*mask*(predict_boardcast_subtrahend-predict_boardcast_minuend)),[1,2])
    print(loss,loss.eval())
    print((tf.reduce_mean(loss)).eval())
    return loss,tf.reduce_mean(loss)


In [5]:
batch_size=2
num_classes=3

sess = tf.InteractiveSession()
predict=np.random.uniform(size=(batch_size,num_classes,1))
# predict_wtf=tf.random_uniform([batch_size,num_labels],minval=0,maxval=1,dtype=tf.float32)
predict=tf.constant(predict)
ground_truth = tf.constant([[0,1,1],[1,0,1]],dtype=tf.float64)
bpmll(predict,ground_truth)

[ 2.  2.]
[ 1.  1.]
Tensor("truediv_1:0", shape=(2,), dtype=float64)
[ 0.5  0.5]
Tensor("Const_4:0", shape=(2, 3, 1), dtype=float64)
[[[ 0.20259959]
  [ 0.32199841]
  [ 0.89491252]]

 [[ 0.5709853 ]
  [ 0.60485487]
  [ 0.58093817]]]
Tensor("Const_5:0", shape=(2, 3), dtype=float64)
[[ 0.  1.  1.]
 [ 1.  0.  1.]]
Tensor("Tile_2:0", shape=(2, 3, 3), dtype=float64)
[[[ 0.20259959  0.20259959  0.20259959]
  [ 0.32199841  0.32199841  0.32199841]
  [ 0.89491252  0.89491252  0.89491252]]

 [[ 0.5709853   0.5709853   0.5709853 ]
  [ 0.60485487  0.60485487  0.60485487]
  [ 0.58093817  0.58093817  0.58093817]]]
Tensor("transpose_2:0", shape=(2, 3, 3), dtype=float64)
[[[ 0.20259959  0.32199841  0.89491252]
  [ 0.20259959  0.32199841  0.89491252]
  [ 0.20259959  0.32199841  0.89491252]]

 [[ 0.5709853   0.60485487  0.58093817]
  [ 0.5709853   0.60485487  0.58093817]
  [ 0.5709853   0.60485487  0.58093817]]]
mask
[[[ 0.  0.  0.]
  [ 1.  0.  0.]
  [ 1.  0.  0.]]

 [[ 0.  1.  0.]
  [ 0.  0.  0.]
  [ 0

(<tf.Tensor 'mul_9:0' shape=(2,) dtype=float64>,
 <tf.Tensor 'Mean_3:0' shape=() dtype=float64>)